name: better_video_player
description: Advanced video player based on video_player.
version: 1.4.0
homepage: https://github.com/WangYng
repository: https://github.com/WangYng/better_video_player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: any
  wakelock_plus: any
  visibility_detector: any
  video_player: any
  provider: any
  connectivity:
    git:
      url: https://github.com/karim-mvp/fork_connectivity_package.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.wangyng.better_video_player
        pluginClass: BetterVideoPlayerPlugin
      ios:
        pluginClass: BetterVideoPlayerPlugin
